.TH "hooks Directory Reference" 3 "Thu Jan 29 2015" "testintegration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hooks Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgithookcontroller\&.py\fP"
.br
.ti -1c
.RI "file \fBpost-commit\&.py\fP"
.br
.ti -1c
.RI "file \fBpre-commit\&.py\fP"
.br
.ti -1c
.RI "file \fBpre-push\&.py\fP"
.br
.in -1c
