.TH "githookcontroller.py" 3 "Tue Jan 27 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
githookcontroller.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgithookcontroller\&.GitHookController\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBgithookcontroller\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgithookcontroller\&.main\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBgithookcontroller\&.log\fP = logging\&.getLogger( 'githookcontroller' )"
.br
.ti -1c
.RI "tuple \fBgithookcontroller\&.ch\fP = logging\&.StreamHandler( sys\&.stdout )"
.br
.ti -1c
.RI "tuple \fBgithookcontroller\&.formatter\fP = logging\&.Formatter( '%(levelname)s (%(name)s): %(message)s' )"
.br
.ti -1c
.RI "tuple \fBgithookcontroller\&.Push\fP"
.br
.ti -1c
.RI "tuple \fBgithookcontroller\&.Commit\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
