.TH "githookcontroller" 3 "Tue Jan 27 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
githookcontroller \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGitHookController\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBlog\fP = logging\&.getLogger( 'githookcontroller' )"
.br
.ti -1c
.RI "tuple \fBch\fP = logging\&.StreamHandler( sys\&.stdout )"
.br
.ti -1c
.RI "tuple \fBformatter\fP = logging\&.Formatter( '%(levelname)s (%(name)s): %(message)s' )"
.br
.ti -1c
.RI "tuple \fBPush\fP"
.br
.ti -1c
.RI "tuple \fBCommit\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def githookcontroller\&.main ()"

.PP
Definition at line 345 of file githookcontroller\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "tuple githookcontroller\&.ch = logging\&.StreamHandler( sys\&.stdout )"

.PP
Definition at line 36 of file githookcontroller\&.py\&.
.SS "tuple githookcontroller\&.Commit"
\fBInitial value:\fP
.PP
.nf
1 = namedtuple('Commit', ['local_ref', 'local_sha1', 'remote_ref', 'remote_sha1',
2                                'local_branch', 'remote_branch'])
.fi
.PP
Definition at line 44 of file githookcontroller\&.py\&.
.PP
Referenced by githookcontroller\&.GitHookController\&.parse_pre_push()\&.
.SS "tuple githookcontroller\&.formatter = logging\&.Formatter( '%(levelname)s (%(name)s): %(message)s' )"

.PP
Definition at line 38 of file githookcontroller\&.py\&.
.SS "tuple githookcontroller\&.log = logging\&.getLogger( 'githookcontroller' )"

.PP
Definition at line 34 of file githookcontroller\&.py\&.
.SS "tuple githookcontroller\&.Push"
\fBInitial value:\fP
.PP
.nf
1 = namedtuple('Push', ['commits', 'remote_name', 'remote_url',
2                            'current_branch', 'removing_remote', 'forcing'])
.fi
.PP
Definition at line 42 of file githookcontroller\&.py\&.
.PP
Referenced by githookcontroller\&.GitHookController\&.parse_pre_push()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
