githookcontroller.GitHookController
NAME
githookcontroller.GitHookController -
SYNOPSIS
Public Member Functions
def __init__
The constructor.
def root_name
git helper functions ###
def remote_root_name
Get root name of remote (the original repo name)
def remote_url
Get url from remote.
def current_branch
Get currently chosen branch.
def remote_branches
Get list of remote branches.
def checkout_branch
Checkout another branch.
def post_commit
functions for hooks ###
def parse_pre_commit
Get list of chagend files in commit.
def parse_pre_push
Parse message from pre-push.
def check_cpplint
functions for code style enforcment ###
def prepare_doxygen_cfg
functions for doxygen integration ###
def publish_doxygen
Checkout all doygen folders in gh-pages branch and commit changes.
def update_doxygen
Update the doxygen documentation for this folder repo.
Public Attributes
args
stdin
parser
organisation
tempdir
vetobranches
doxy_enforce_repos
Private Member Functions
def _get_doxygen_warnings
Get all doxygen warnings.
Detailed Description
Definition at line 47 of file githookcontroller.py.
Constructor & Destructor Documentation
def githookcontroller.GitHookController.__init__ (self, tempdir = '/tmp/')
The constructor.
Parameters:
self The object pointer
tempdir Directory where files are stored temporarily outside the repo default: /tmp/
Definition at line 53 of file githookcontroller.py.
Member Function Documentation
def githookcontroller.GitHookController._get_doxygen_warnings (self) [private]
Get all doxygen warnings.
Definition at line 438 of file githookcontroller.py.
Referenced by githookcontroller.GitHookController.update_doxygen().
def githookcontroller.GitHookController.check_cpplint (self, filepath)
functions for code style enforcment ### Check if file fullfills cpplint check
Parameters:
self The object pointer
filepath path to the file where lint check should be performed
Definition at line 246 of file githookcontroller.py.
def githookcontroller.GitHookController.checkout_branch (self, branchname, forced = False)
Checkout another branch.
Parameters:
self The object pointer
branchname name of branch which is checked out
forced boolean for forced checkout
Definition at line 161 of file githookcontroller.py.
Referenced by githookcontroller.GitHookController.publish_doxygen().
def githookcontroller.GitHookController.current_branch (self)
Get currently chosen branch.
Definition at line 138 of file githookcontroller.py.
Referenced by githookcontroller.GitHookController.prepare_doxygen_cfg(), githookcontroller.GitHookController.publish_doxygen(), and githookcontroller.GitHookController.update_doxygen().
def githookcontroller.GitHookController.parse_pre_commit (self)
Get list of chagend files in commit.
Parameters:
self The object pointer
Definition at line 182 of file githookcontroller.py.
def githookcontroller.GitHookController.parse_pre_push (self)
Parse message from pre-push. Based on example in: http://axialcorps.com/2014/06/03/preventing-errant-git-pushes-with-a-pre-push-hook/
Parameters:
self The object pointer
Returns:
namedtupe of type Push fields: ['commits', 'remote_name', 'remote_url','current_branch', 'removing_remote', 'forcing']
Definition at line 200 of file githookcontroller.py.
References githookcontroller.Commit, and githookcontroller.Push.
def githookcontroller.GitHookController.post_commit (self)
functions for hooks ### Parse message from post commit
Parameters:
self The object pointer
Definition at line 176 of file githookcontroller.py.
def githookcontroller.GitHookController.prepare_doxygen_cfg (self)
functions for doxygen integration ### Prepare doxygen config file from template
The function replaces Tokens for files in ./doc/:
template_cfg available Tokens: branchname% current branch name remote_root_name% html_header% path to html header file html_footer% path to html header file
header_template.html
footer_template.html available Tokens: +++optionsline+++ a fixed url path ++branch_name++ current branch name ++remote_url++ see object property ++remote_root_name++ see object property
Parameters:
self The object pointer
Definition at line 271 of file githookcontroller.py.
References githookcontroller.GitHookController.current_branch(), githookcontroller.GitHookController.organisation, githookcontroller.GitHookController.remote_branches(), githookcontroller.GitHookController.remote_root_name(), githookcontroller.GitHookController.remote_url(), and githookcontroller.GitHookController.vetobranches.
def githookcontroller.GitHookController.publish_doxygen (self, branchnames)
Checkout all doygen folders in gh-pages branch and commit changes.
Definition at line 337 of file githookcontroller.py.
References githookcontroller.GitHookController.checkout_branch(), and githookcontroller.GitHookController.current_branch().
def githookcontroller.GitHookController.remote_branches (self)
Get list of remote branches.
Returns:
A list of strings containing all remot branch names
Definition at line 148 of file githookcontroller.py.
Referenced by githookcontroller.GitHookController.prepare_doxygen_cfg().
def githookcontroller.GitHookController.remote_root_name (self)
Get root name of remote (the original repo name)
Returns:
string containing the name of the remote root name
Definition at line 86 of file githookcontroller.py.
Referenced by githookcontroller.GitHookController.prepare_doxygen_cfg().
def githookcontroller.GitHookController.remote_url (self)
Get url from remote.
Returns:
string containing the name of the remote root name
Definition at line 103 of file githookcontroller.py.
Referenced by githookcontroller.GitHookController.prepare_doxygen_cfg().
def githookcontroller.GitHookController.root_name (self)
git helper functions ### Get root name of repo
Returns:
string containing the name of the root name
Definition at line 76 of file githookcontroller.py.
Referenced by githookcontroller.GitHookController.update_doxygen().
def githookcontroller.GitHookController.update_doxygen (self, configpath = './doc/doxy_cfg')
Update the doxygen documentation for this folder repo. Based on example in: http://axialcorps.com/2014/06/03/preventing-errant-git-pushes-with-a-pre-push-hook/
Parameters:
self The object pointer
configpath Path to the doxygen confi file
Definition at line 404 of file githookcontroller.py.
References githookcontroller.GitHookController._get_doxygen_warnings(), githookcontroller.GitHookController.current_branch(), githookcontroller.GitHookController.doxy_enforce_repos, githookcontroller.GitHookController.root_name(), and githookcontroller.GitHookController.vetobranches.
Member Data Documentation
githookcontroller.GitHookController.args
Definition at line 54 of file githookcontroller.py.
githookcontroller.GitHookController.doxy_enforce_repos
Definition at line 65 of file githookcontroller.py.
Referenced by githookcontroller.GitHookController.update_doxygen().
githookcontroller.GitHookController.organisation
Definition at line 59 of file githookcontroller.py.
Referenced by githookcontroller.GitHookController.prepare_doxygen_cfg().
githookcontroller.GitHookController.parser
Definition at line 57 of file githookcontroller.py.
githookcontroller.GitHookController.stdin
Definition at line 55 of file githookcontroller.py.
githookcontroller.GitHookController.tempdir
Definition at line 60 of file githookcontroller.py.
githookcontroller.GitHookController.vetobranches
Definition at line 62 of file githookcontroller.py.
Referenced by githookcontroller.GitHookController.prepare_doxygen_cfg(), and githookcontroller.GitHookController.update_doxygen().
Author
Generated automatically by Doxygen for testintegration from the source code.