.TH "pre-commit" 3 "Tue Jan 27 2015" "libs3a" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pre-commit \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBgitController\fP = \fBGitHookController\fP()"
.br
.ti -1c
.RI "tuple \fBchanged\fP = gitController\&.parse_pre_commit()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple pre-commit\&.changed = gitController\&.parse_pre_commit()"

.PP
Definition at line 11 of file pre-commit\&.py\&.
.SS "tuple pre-commit\&.gitController = \fBGitHookController\fP()"

.PP
Definition at line 9 of file pre-commit\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libs3a from the source code\&.
