.TH "dummycode.dummy" 3 "Thu Jan 29 2015" "testintegration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dummycode.dummy \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBsome_func\fP"
.br
.RI "\fIsome info \fP"
.ti -1c
.RI "def \fBsome_func3\fP"
.br
.RI "\fIsome info \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdd\fP"
.br
.ti -1c
.RI "\fBaa\fP"
.br
.ti -1c
.RI "\fBbb\fP"
.br
.ti -1c
.RI "\fBxx\fP"
.br
.ti -1c
.RI "\fByy\fP"
.br
.ti -1c
.RI "\fBll\fP"
.br
.ti -1c
.RI "\fBpp\fP"
.br
.ti -1c
.RI "\fBww\fP"
.br
.ti -1c
.RI "\fBoo\fP"
.br
.ti -1c
.RI "\fBtt\fP"
.br
.ti -1c
.RI "\fBzz\fP"
.br
.ti -1c
.RI "\fBddjal\fP"
.br
.ti -1c
.RI "\fBtaat\fP"
.br
.ti -1c
.RI "\fBtkkt\fP"
.br
.ti -1c
.RI "\fBzzz\fP"
.br
.ti -1c
.RI "\fBkssdd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file dummycode\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def dummycode\&.dummy\&.__init__ (self)"

.PP
Definition at line 2 of file dummycode\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def dummycode\&.dummy\&.some_func (self, par)"

.PP
some info 
.PP
\fBParameters:\fP
.RS 4
\fIself\fP pointer 
.br
\fIpar\fP A par 
.RE
.PP

.PP
Definition at line 35 of file dummycode\&.py\&.
.SS "def dummycode\&.dummy\&.some_func3 (self, par)"

.PP
some info 
.PP
\fBParameters:\fP
.RS 4
\fIself\fP pointer 
.br
\fIpar\fP A par 
.RE
.PP

.PP
Definition at line 42 of file dummycode\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "dummycode\&.dummy\&.aa"

.PP
Definition at line 4 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.bb"

.PP
Definition at line 5 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.dd"

.PP
Definition at line 3 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.ddjal"

.PP
Definition at line 14 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.kssdd"

.PP
Definition at line 26 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.ll"

.PP
Definition at line 8 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.oo"

.PP
Definition at line 11 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.pp"

.PP
Definition at line 9 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.taat"

.PP
Definition at line 23 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.tkkt"

.PP
Definition at line 24 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.tt"

.PP
Definition at line 12 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.ww"

.PP
Definition at line 10 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.xx"

.PP
Definition at line 6 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.yy"

.PP
Definition at line 7 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.zz"

.PP
Definition at line 13 of file dummycode\&.py\&.
.SS "dummycode\&.dummy\&.zzz"

.PP
Definition at line 25 of file dummycode\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for testintegration from the source code\&.
